### ISSUE TITLE
fix sudo issue with Golang/Clone roles

### ISSUE THREAD

**Issue by dborg92** [Senior-Design-May1601/config#22]
need to perform actions as sudo as little as possible.

**Comment by nskinkel** [comment]
This is a regression. Check a2446fcbcc89a20232a5836cb7b2ceaf1d619a40 for an example of doing this as an unprivileged user.

**Comment by dborg92** [comment]
the difference between this old build and current  stems from variations in clone role. differences are: previous working build used File module which builds the directory with supplied permissions. in that task, i believe it was created as deploy user. i can't seem to do the same in the shell module without using sudo. I also can't create the directory via ssh-ing in, su to deploy, and executing the command. any idea's? is there another way to make a directory with shell besides mkdir?

specifically, i need to identify who specifically i should be when making this directory, because if i make it with sudo, the permissions seem cause a chain reaction, requiring the git command to be done in sudo , requiring subsequent roles to be sudo as well.

**Comment by nskinkel** [comment]
Please read some linux/unix permissions tutorials, such as http://www.tutorialspoint.com/unix/unix-file-permission.htm, https://www.nersc.gov/users/storage-and-file-systems/unix-file-permissions/, or http://www.ee.surrey.ac.uk/Teaching/Unix/unix5.html.

You should absolutely not be cloning repositories as the root user. It is not possible to answer your other questions without more information.

Please get into the habit of posting exact terminal outputs, steps to reproduce, etc. when commenting on bug stuff. Otherwise it's not possible to diagnose.

You have a completely working version in a2446fc, so just read through that, identify the differences, and that will tell you where the regression was.

**Comment by dborg92** [comment]
a2446fc is not a working version, as of ansible 2.0.2  and the introduction of the 'file module' bug. I may try re-installing ansible from source in hopes of fixing this.

**Comment by nskinkel** [comment]
Yes it is. It was written using Ansible 1.9, and therefore works with Ansible 1.9. To see this, uninstall any version of Ansible that is not 1.9, and then do something like

`
pip install ansible==1.9
`

(I think that's the right pip syntax to install a specific ansible version, but that command isn't actually tested)

**Comment by dborg92** [comment]
issue is fixed. ansible version 2.0.1 provides needed support and fixes this bug.
